### ISSUE TITLE
Natives not found

### ISSUE THREAD

**Issue by crodriguespt** [Zeex/sampgdk#127]
I noticed today that we cannot use sa-mp server natives before OnGameModeInit
Basically, I tried to run SendRconCommand on Supports function, and I'm getting "Native not found"
And on "OnGameModeInit", it's working perfectly.

Wasn't sampgdk::Load the "trigger" to load up every sa-mp server native?

My idea was to set the hostname, mapname and gamemodetext before ongamemodeinit, just like in PAWN @main function.

**Comment by Zeex** [comment]
GDK hooks amx_Register to collect addresses of all natives, so you can't call them before they are registered by the server or other plugins, and that happens when all plugins are already loaded.  Therefore Load can't be used for that purpose.

In theory the earliest point at which you can make calls to SA-MP natives seems to be AmxLoad, but I haven't tested that. For other plugin's natives it depends on the plugin order. You could also execute something before OnGameModeInit by catching it inside OnPublicCall.

Anyway I don't really understand why would you want to call things before OnGameModeInit, it's a perfect place for doing stuff like you mentioned. BTW main() is actually called *after* OnGameModeInit in SA-MP.

**Comment by crodriguespt** [comment]
```
Anyway I don't really understand why would you want to call things before OnGameModeInit, it's a perfect place for doing stuff like you mentioned. BTW main() is actually called after OnGameModeInit in SA-MP.
```
I'm just screwing around in C/++, and when I noticed this "issue", I thought in reporting it.
Anyways, thanks for clarifying!

**Comment by Zeex** [comment]
OK, thanks for reporting it anyway :+1: I think I should make a better error mesage for this as you're not the first person asking about it.
