### ISSUE TITLE
Help with OnPlayerCommandText

### ISSUE THREAD

**Issue by uMarcelo** [Zeex/sampgdk#128]
Hello, i am from Russia, pardon the grammar (i am use google translate)

Who can give me an example with the work with sscanf (for example, /pm playerid text), thanks in advance..

**Comment by uMarcelo** [comment]
please help guys!!

**Comment by ikkentim** [comment]
Please note this is not a help forum. Issues are for reporting bugs or problems with sampgdk. For help with C++ I either suggest searching on google or reading C++ tutorials.

If you'd have searched on google, you'd have found this: http://www.cplusplus.com/reference/cstdio/sscanf/

**Comment by Zeex** [comment]
I'm afraid you can't use the sscanf plugin in C++ as it's tailored specifically towards Pawn scripting. Well, to some extent you can but I wouldn't ecommend doing that.

As it was pointed out by @ikkentim in C/C++ there's a built-in function with the same name does nearly the same thing. However, it's generally not recommended to use because it's not protected from buffer overflows and considered not type-safe.

C++ is a much reacher language than Pawn, in terms of both features and libraries, so there are [many ways](http://stackoverflow.com/questions/236129/split-a-string-in-c) to split a string. There are also [regular expressions](http://msdn.microsoft.com/en-us/magazine/dn519920.aspx).
