### ISSUE TITLE
SetTimer params

### ISSUE THREAD

**Issue by Vinigas** [Zeex/sampgdk#143]
Hi,
could you show me some simple example of using SetTimer with *params.

For e.g.:

struct Params {
    int x;
    int y;
    Params(const int & x, const int & y) : x(x), y(y){ }
};
...
SetTimer(1000, false, TimerCallback, new Params(10, 20));
...
void SAMPGDK_CALL TimerCallback(int timerid, void *params)
{
    Params *p = (Params*)params;
    someFunction(p->x);
    someFunction(p->y);

    delete params;
}

Do I use it correctly ? Maybe I dont need to use new and delete  because SetTimer is saving information for callback ?
Maybe should I use *params to put C-string (char) and use stringstream in callback ?

Thanks very much for answering!

**Comment by Zeex** [comment]
That looks like right, yeah. Just one little thing - if that timer repeats (i.e. repeat = true in SetTimerEx) you don't want to delete params inside the callback because it will be passed on the next call.

SetTimerEx saves only the pointer to your data, not the data itself, so you can't use local variables there or anything whose lifetime ends before the timer stops.

**Comment by Zeex** [comment]
Assuming the question has been answered. If not, feel free to reopen.
