### ISSUE TITLE
suggested / preffered windows ide / compiler

### ISSUE THREAD

**Issue by JernejL** [Zeex/sampgdk#145]
I know cmake can make a lot of solutions for various ides and compiler, but what do you suggest is best suitable for new projects using sampgdk? A (specific) version of Visual C++ (what version is minimally needed? ) or would code:.blocks with mingw will work just as good?

**Comment by Zeex** [comment]
Yes, Code blocks and MinGW will work too. The library itself should compile with about any C compiler since it's written in C89, it mostly depends on your plugin's code.

If you care about latest C++ features from C++14 you should probably use Visual Studio 2013 (or even 2015) or GCC 5.0, otherwise you can use whatever IDE/compiler you're already using.

**Comment by Zeex** [comment]
Did this answer your question?

**Comment by JernejL** [comment]
Yep i think i'll get it working. i will try code::blocks first since i can't install any visual studio.. it demands 8gb of space from me on system drive which i don't have (it's only a 64gb SSD and windows 7 takes its toll)
