### ISSUE TITLE
SHA256_PassHash missing

### ISSUE THREAD

**Issue by 123marvin123** [Zeex/sampgdk#154]
The new password hashing function, introduced in 0.3.7, is missing.

**Comment by ikkentim** [comment]
You better use hashing methods supplied by your language of choice. A direct call to a sha256 hashing method is much faster than using the one supplied by samp, because you'd need to go all the way trough the pawn vm. Or, in your case, simply use a java sha256 function.

http://stackoverflow.com/questions/3103652/hash-string-via-sha-256-in-java

In short, using a direct implementation of computing functions are much faster than going all the way trough the pawn vm. Same goes for the math, string and http functions.

**Comment by 123marvin123** [comment]
I know, but I think it still should be added.

**Comment by kurta999** [comment]
Do not use anything, which were designed by NSA :)
