### ISSUE TITLE
OnPublicCall in fs

### ISSUE THREAD

**Issue by piatus** [Zeex/sampgdk#160]
Hello,  
I'm having a problem with OnPublicCall, it's getting called only for the gamemode

`   public OnFilterScriptInit()
    {

```
    CallRemoteFunction("OnPlayerDeath","iii",5,4,3);
    return 1;
}
```

`

return

> gamemode 5 24 24
> filterscript 5 4 3

`
PLUGIN_EXPORT bool PLUGIN_CALL OnPublicCall(AMX *amx, const char *name, cell *params, cell *retval)
{
    auto Name = std::string(name);

```
if (Name.compare("OnPlayerDeath") == 0)
{
    if (params[0] == 16) return true;
    int idx;

    if (!amx_FindPublic(amx, "OnPlayerDeath", &idx))
    {


        int weaponid = 24;
        int killerid = 24;


        amx_Push(amx, static_cast<cell>(rand() % 5000)); //check params[0]==16 (stunff)
        amx_Push(amx, static_cast<cell>(weaponid));
        amx_Push(amx, static_cast<cell>(killerid));
        amx_Push(amx, static_cast<cell>(params[1]));

        amx_Exec(amx, retval, idx);

        return false;

    }

}


return true;
```

}`

**Comment by ikkentim** [comment]
It's not a bug. Filterscripts are *filter* scripts. These scripts are invoked before all other scripts, including gamemodes and plugins (which use sampgdk).

Call order:
* Filterscripts
* Plugins
* Gamemodes

**Comment by Peter-Harmann** [comment]
While ikkentim answer is true, I also wanted to do something similar to you, so I have solved this problem using small rewrite of sampgdk.

https://www.dropbox.com/s/1uv48pn0kwih9z4/sampgdk.c?dl=0

In your plugin, add function
`extern "C" int OnPublicBlocker(AMX *amx, cell *retval, int index) {}`
and import variable
`extern "C" cell no_public_blocking_retval;`

The function will be called when **a FILTERSCRIPT** call a public. You can block execution of the public by returning false. Otherwise return true. 
The no_public_blocking_retval should be used in amx_Exec as retval in your plugin, so that calls from your plugin do not call OnPublicBlocker, otherwise you may create infinite loop.

**Comment by samphunter** [comment]
While ikkentim answer is true, I also wanted to do something similar to you, so I have solved this problem using small rewrite of sampgdk.

https://www.dropbox.com/s/1uv48pn0kwih9z4/sampgdk.c?dl=0

In your plugin, add function
`extern "C" int OnPublicBlocker(AMX *amx, cell *retval, int index) {}`
and import variable
`extern "C" cell no_public_blocking_retval;`

The function will be called when **a FILTERSCRIPT** call a public. You can block execution of the public by returning false. Otherwise return true. 
The no_public_blocking_retval should be used in amx_Exec as retval in your plugin, so that calls from your plugin do not call OnPublicBlocker, otherwise you may create infinite loop.
