### ISSUE TITLE
Callbacks aren't called

### ISSUE THREAD

**Issue by IstuntmanI** [Zeex/sampgdk#171]
I am using the sample helloworld gamemode. With sampgdk 4.5 callbacks are called, but with sampgdk 4.5.1 they aren't. Another guy also confirmed this.

**Comment by WopsS** [comment]
For me it works just fine, I I downloaded the source code from the **git** and compiled it.
![image](https://cloud.githubusercontent.com/assets/3403191/22840920/1803753c-efd8-11e6-8652-6b7bbe4c2d92.png)

**Comment by IstuntmanI** [comment]
Weird. This is how I tried it:
https://mega.nz/#!S0wzFZwT!Wg84VD6LCbiRqLZBtSeev440cow_n0ulWUROQMFyfD4
Maybe it is related to some flags.

By the way, I am using maddinat0r's sampsdk, the one from Zeex was giving me warnings, if I remember correctly. Try to compile what is in that archive.

**Comment by Zeex** [comment]
Thanks, I fixed this in c327e43e. It will be available in 4.5.2.

P.S. SA-MP SDK may give you warnings because of some stuff in AMX headers. You can alternatively [`#include <sampgdk/sdk.h>`](https://github.com/Zeex/sampgdk/blob/master/include/sampgdk/sdk.h#L23-L70) instead which is basically the same thing but with various workarounds for SDK warnings/errors.
