### ISSUE TITLE
OnVehicleSirenStateChange change type from int to bool

### ISSUE THREAD

**Issue by ghost** [Zeex/sampgdk#209]
Hello
See the documentation samp
https://wiki.sa-mp.com/wiki/OnVehicleSirenStateChange

Method OnVehicleSirenStateChange
has boolean parameter "new state"
0 - false
1 - true

Can you replace the type from an integer to a boolean?

**Comment by Zeex** [comment]
IIRC `newstate` was made an integer so that it could handle other values in the future besides 0 and 1. Like the name implies, it's not really a boolean but rather a state index. For example, at some point, the SA-MP devs could introduce `newstate = 2` to handle a different state. I have no idea if this ever happens (probably not), but I'd like to not lock the parameter to just 0/1.

So I'll leave it as `int`. But thank you for the suggestion.
